### PR TITLE
Rewrite of the iOS part of the plugin

### PR DESCRIPTION
**Pull request by jeroentrappers**
This is a first draft implementation, which still needs some cleaning up.

### CODE REVIEW

**Comment by devgeeks** [comment]
Ooh, so is this a blur instead of using the splashscreen?

**Comment by anri-asaturov** [comment]
Nice, this PR fixed ios issues, plz merge it.

**Comment by devgeeks** [comment]
@jeroentrappers What kind of "cleaning up" do you forsee? Overall I really like this. I think I might massage the animation duration and the blur radius, but otherwise...

**Comment by jeroentrappers** [comment]
Just removing commented out code in the javascript... can be merged as is.

**Comment by devgeeks** [comment]
:+1:

**Comment by devgeeks** [comment]
I am loving this... but I am having a slight problem I need to work out.

It works perfect on the iOS simulator, but when I build an archive .ipa for ad hoc distribution it doesn't blur, just makes the entire app white. It's weird. I am going to test it on a non archive install on a device and see if there are any errors etc.

**Comment by devgeeks** [comment]
@jeroentrappers any ideas?

**Comment by jeroentrappers** [comment]
hi @devgeeks 
I've added a preloading of the blurview and tested on device. It seems that on device the first blurring is otherwise too late to be an effective privacy screen.

**Comment by devgeeks** [comment]
Nice! I suspected it was a race condition based on speed (devices being slower than the sim).

I'll test this out asap.

**Comment by jeroentrappers** [comment]
@devgeeks I've found and fixed the issue when interacting with WKWebView (Telerik plugin)

**Comment by jeroentrappers** [comment]
My client asked to have an opaque option as well, so I added it :-)

**Comment by devgeeks** [comment]
:+1:  Will test and hopefully merge today.

**Comment by devgeeks** [comment]
Would love to revisit this some time...

**Pull request closed without merging**
